# Generated by Django 3.1.1 on 2020-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0003_auto_20201102_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
