# Generated by Django 3.1.1 on 2020-11-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0007_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='money_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='money_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
