# Generated by Django 3.1.1 on 2020-11-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0006_event_location'),
        ('tinyfunds', '0008_auto_20201109_0342'),
    ]

    operations = [
    ]
