# Generated by Django 3.1.1 on 2020-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0008_auto_20201109_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
