# Generated by Django 3.1.1 on 2020-11-09 05:27

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0011_auto_20201109_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=places.fields.PlacesField(default=('Metrocentro, Managua, Nicaragua', 52.522906, 13.41156), max_length=255),
            preserve_default=False,
        ),
    ]
