# Generated by Django 3.1.1 on 2020-11-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0014_auto_20201109_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='address',
        ),
    ]
