# Generated by Django 3.1.1 on 2020-11-09 16:26

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0015_auto_20201109_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=places.fields.PlacesField(default='Virginia, 38.02, 78.511', max_length=255),
        ),
    ]
