# Generated by Django 3.1.1 on 2020-11-09 17:24

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0017_auto_20201109_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=places.fields.PlacesField(blank=True, default='University of Virginia, 38, 78.5', max_length=255),
        ),
    ]
