# Generated by Django 3.1.1 on 2020-11-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0018_auto_20201109_1724'),
        ('tinyfunds', '0009_pledge_confirmed'),
    ]

    operations = [
    ]
