# Generated by Django 3.1.1 on 2020-11-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0021_auto_20201109_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
