# Generated by Django 3.1.1 on 2020-11-10 20:06

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0024_auto_20201109_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=places.fields.PlacesField(blank=True, max_length=255, verbose_name='Event Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='money_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Donation Goal'),
        ),
        migrations.AlterField(
            model_name='event',
            name='org_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.CharField(default='https://avatars2.githubusercontent.com/u/3195011?s=460&u=f421eadccb78b212d516b6b38cab7f2de97522e4&v=4', max_length=1024, verbose_name='Event Picture'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Event Name'),
        ),
    ]
