# Generated by Django 3.1.1 on 2020-11-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0025_auto_20201110_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
