# Generated by Django 3.1.1 on 2020-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0027_auto_20201117_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hours_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
