# Generated by Django 3.1.1 on 2020-11-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0028_event_hours_received'),
        ('tinyfunds', '0028_auto_20201117_2224'),
    ]

    operations = [
    ]
