# Generated by Django 3.1.1 on 2020-11-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfunds', '0029_merge_20201117_2226'),
        ('tinyfunds', '0028_auto_20201117_2032'),
    ]

    operations = [
    ]
