# Generated by Django 3.1.1 on 2020-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_total_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_hours_pledged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
